name: Trigger auto deployment for demofastapi

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/demofastapi-AutoDeployTrigger-4d6ba25a-29f6-453a-ba69-8d672d204ec2.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.DEMOFASTAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DEMOFASTAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DEMOFASTAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.DEMOFASTAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DEMOFASTAPI_REGISTRY_PASSWORD }}
          containerAppName: demofastapi
          resourceGroup: demo
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


