name: Show Event Info

on:
  workflow_dispatch:
  push:

jobs:
  show:
    runs-on: ubuntu-latest

    steps:
      - name: Print event name
        run: echo "Event Name = $GITHUB_EVENT_NAME"

      - name: Print full event payload
        run: |
          echo "====== EVENT PAYLOAD ======"
          cat "$GITHUB_EVENT_PATH"

      - name: Print Github context
        run: |
          echo "====== GITHUB CONTEXT ======"
          echo "${{ toJson(github) }}"

      - name: Print environment variables
        run: |
          echo "====== ENVIRONMENT VARS ======"
          env | sort
